import type { ProviderDefinition, ProviderId } from "./types";

/**
 * Provider Catalog
 * ----------------
 * Static metadata for every supported provider. Adding a new provider is
 * a one-line operation: append a definition here, ensure its protocol is
 * handled in `adapters.ts`, and the picker / settings UI will pick it up
 * automatically.
 */
export const PROVIDER_CATALOG: ProviderDefinition[] = [
  {
    id: "gateway",
    name: "Vercel AI Gateway",
    arabicName: "بوابة Vercel للذكاء الاصطناعي",
    description:
      "Zero-config access to 200+ models (OpenAI, Anthropic, Google, Llama…) through one key.",
    arabicDescription:
      "وصول فوري لأكثر من 200 نموذج (OpenAI و Anthropic و Google و Llama) عبر مفتاح واحد.",
    protocol: "openai-chat",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    docsUrl: "https://vercel.com/docs/ai-gateway",
    apiKeyUrl: "https://vercel.com/dashboard/ai-gateway",
    serverEnvKey: "AI_GATEWAY_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#0F172A",
    popularModels: [
      {
        id: "openai/gpt-4o",
        name: "openai/gpt-4o",
        label: "GPT-4o",
        provider: "gateway",
        contextWindow: 128000,
        maxOutput: 16384,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "OpenAI flagship multimodal model via the AI Gateway.",
        arabicDescription: "نموذج OpenAI الرئيسي متعدد الوسائط عبر البوابة.",
      },
      {
        id: "openai/gpt-4o-mini",
        name: "openai/gpt-4o-mini",
        label: "GPT-4o mini",
        provider: "gateway",
        contextWindow: 128000,
        maxOutput: 16384,
        supportsVision: true,
        supportsTools: true,
        pricing: "freemium",
        description: "Fast, affordable default — great for everyday chat.",
        arabicDescription: "سريع واقتصادي — مثالي للاستخدام اليومي.",
      },
      {
        id: "anthropic/claude-sonnet-4.5",
        name: "anthropic/claude-sonnet-4.5",
        label: "Claude Sonnet 4.5",
        provider: "gateway",
        contextWindow: 200000,
        maxOutput: 16000,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Best balance of intelligence and speed from Anthropic.",
        arabicDescription: "أفضل توازن بين الذكاء والسرعة من Anthropic.",
      },
      {
        id: "google/gemini-2.5-pro",
        name: "google/gemini-2.5-pro",
        label: "Gemini 2.5 Pro",
        provider: "gateway",
        contextWindow: 1000000,
        maxOutput: 8192,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Google's top model with a huge context window.",
        arabicDescription: "أقوى نماذج Google بنافذة سياق ضخمة.",
      },
      {
        id: "google/gemini-2.5-flash",
        name: "google/gemini-2.5-flash",
        label: "Gemini 2.5 Flash",
        provider: "gateway",
        contextWindow: 1000000,
        supportsVision: true,
        pricing: "freemium",
        description: "Fast, lightweight multimodal with 1M context.",
        arabicDescription: "سريع وخفيف متعدد الوسائط بسياق 1M.",
      },
      {
        id: "deepseek/deepseek-v3.1",
        name: "deepseek/deepseek-v3.1",
        label: "DeepSeek V3.1",
        provider: "gateway",
        contextWindow: 64000,
        pricing: "freemium",
        description: "Strong open reasoning model, low cost.",
        arabicDescription: "نموذج استدلالي مفتوح قوي ومنخفض التكلفة.",
      },
      {
        id: "meta/llama-3.3-70b",
        name: "meta/llama-3.3-70b",
        label: "Llama 3.3 70B",
        provider: "gateway",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Meta's latest 70B instruct model.",
        arabicDescription: "أحدث نموذج 70B من Meta.",
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    arabicName: "OpenAI",
    description: "GPT-4o, o1, o3 and the full OpenAI model lineup.",
    arabicDescription: "نماذج GPT-4o و o1 و o3 من OpenAI.",
    protocol: "openai-chat",
    baseUrl: "https://api.openai.com/v1",
    docsUrl: "https://platform.openai.com/docs",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    serverEnvKey: "OPENAI_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#10A37F",
    popularModels: [
      {
        id: "gpt-4o",
        name: "gpt-4o",
        label: "GPT-4o",
        provider: "openai",
        contextWindow: 128000,
        maxOutput: 16384,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Flagship multimodal model, fast and versatile.",
        arabicDescription: "النموذج الرئيسي متعدد الوسائط، سريع ومتعدد الاستخدامات.",
      },
      {
        id: "gpt-4o-mini",
        name: "gpt-4o-mini",
        label: "GPT-4o mini",
        provider: "openai",
        contextWindow: 128000,
        maxOutput: 16384,
        supportsVision: true,
        supportsTools: true,
        pricing: "freemium",
        description: "Affordable, intelligent, fast — great default.",
        arabicDescription: "اقتصادي وذكي وسريع — خيار افتراضي ممتاز.",
      },
      {
        id: "o1",
        name: "o1",
        label: "o1",
        provider: "openai",
        contextWindow: 200000,
        maxOutput: 100000,
        supportsVision: true,
        pricing: "paid",
        description: "Reasoning model for complex multi-step problems.",
        arabicDescription: "نموذج استدلالي للمسائل المعقدة متعددة الخطوات.",
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        label: "o3-mini",
        provider: "openai",
        contextWindow: 200000,
        maxOutput: 100000,
        pricing: "paid",
        description: "Latest reasoning model, fast and affordable.",
        arabicDescription: "أحدث نماذج الاستدلال، سريع واقتصادي.",
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    arabicName: "Anthropic",
    description: "Claude 4 Opus, Sonnet, and Haiku with industry-leading context.",
    arabicDescription: "Claude 4 Opus و Sonnet و Haiku بسياق متقدم.",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    docsUrl: "https://docs.anthropic.com",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    serverEnvKey: "ANTHROPIC_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#D97757",
    popularModels: [
      {
        id: "claude-opus-4-1-20250805",
        name: "claude-opus-4-1-20250805",
        label: "Claude Opus 4.1",
        provider: "anthropic",
        contextWindow: 200000,
        maxOutput: 32000,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Most capable Claude model for complex tasks.",
        arabicDescription: "أقوى نموذج Claude للمهام المعقدة.",
      },
      {
        id: "claude-sonnet-4-5-20250929",
        name: "claude-sonnet-4-5-20250929",
        label: "Claude Sonnet 4.5",
        provider: "anthropic",
        contextWindow: 200000,
        maxOutput: 16000,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Best balance of intelligence and speed.",
        arabicDescription: "أفضل توازن بين الذكاء والسرعة.",
      },
      {
        id: "claude-haiku-4-5-20251001",
        name: "claude-haiku-4-5-20251001",
        label: "Claude Haiku 4.5",
        provider: "anthropic",
        contextWindow: 200000,
        maxOutput: 8192,
        supportsVision: true,
        pricing: "freemium",
        description: "Fast and compact for everyday tasks.",
        arabicDescription: "سريع ومضغوط للمهام اليومية.",
      },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    arabicName: "Google Gemini",
    description: "Gemini 2.5 Pro / Flash with massive context windows.",
    arabicDescription: "Gemini 2.5 Pro / Flash بنوافذ سياق ضخمة.",
    protocol: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    serverEnvKey: "GEMINI_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#4285F4",
    popularModels: [
      {
        id: "gemini-2.5-pro",
        name: "gemini-2.5-pro",
        label: "Gemini 2.5 Pro",
        provider: "gemini",
        contextWindow: 2000000,
        maxOutput: 8192,
        supportsVision: true,
        supportsTools: true,
        pricing: "paid",
        description: "Largest context window available, top-tier reasoning.",
        arabicDescription: "أكبر نافذة سياق متاحة، استدعاء من الطراز الأول.",
      },
      {
        id: "gemini-2.5-flash",
        name: "gemini-2.5-flash",
        label: "Gemini 2.5 Flash",
        provider: "gemini",
        contextWindow: 1000000,
        maxOutput: 8192,
        supportsVision: true,
        pricing: "freemium",
        description: "Fast and lightweight with 1M context.",
        arabicDescription: "سريع وخفيف مع سياق 1M.",
      },
      {
        id: "gemini-2.0-flash",
        name: "gemini-2.0-flash",
        label: "Gemini 2.0 Flash",
        provider: "gemini",
        contextWindow: 1000000,
        maxOutput: 8192,
        supportsVision: true,
        pricing: "freemium",
        description: "Production-grade, low-latency multimodal.",
        arabicDescription: "إنتاج متعدد الوسائط بزمن استجابة منخفض.",
      },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    arabicName: "OpenRouter",
    description: "Unified gateway to 200+ models from every major lab.",
    arabicDescription: "بوابة موحدة لأكثر من 200 نموذج من جميع المختبرات.",
    protocol: "openrouter",
    baseUrl: "https://openrouter.ai/api/v1",
    docsUrl: "https://openrouter.ai/docs",
    apiKeyUrl: "https://openrouter.ai/keys",
    serverEnvKey: "OPENROUTER_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#8B5CF6",
    popularModels: [
      {
        id: "anthropic/claude-sonnet-4.5",
        name: "anthropic/claude-sonnet-4.5",
        label: "Claude Sonnet 4.5 (via OpenRouter)",
        provider: "openrouter",
        contextWindow: 200000,
        supportsVision: true,
        pricing: "paid",
        description: "Claude Sonnet 4.5 routed via OpenRouter.",
        arabicDescription: "Claude Sonnet 4.5 عبر OpenRouter.",
      },
      {
        id: "openai/gpt-4o",
        name: "openai/gpt-4o",
        label: "GPT-4o (via OpenRouter)",
        provider: "openrouter",
        contextWindow: 128000,
        supportsVision: true,
        pricing: "paid",
        description: "GPT-4o routed via OpenRouter.",
        arabicDescription: "GPT-4o عبر OpenRouter.",
      },
      {
        id: "google/gemini-2.5-pro",
        name: "google/gemini-2.5-pro",
        label: "Gemini 2.5 Pro (via OpenRouter)",
        provider: "openrouter",
        contextWindow: 2000000,
        supportsVision: true,
        pricing: "paid",
        description: "Gemini 2.5 Pro routed via OpenRouter.",
        arabicDescription: "Gemini 2.5 Pro عبر OpenRouter.",
      },
      {
        id: "deepseek/deepseek-chat-v3.1",
        name: "deepseek/deepseek-chat-v3.1",
        label: "DeepSeek V3.1 (via OpenRouter)",
        provider: "openrouter",
        contextWindow: 64000,
        pricing: "freemium",
        description: "Strong open-source reasoning, low cost.",
        arabicDescription: "استدعاء قوي مفتوح المصدر، تكلفة منخفضة.",
      },
      {
        id: "meta-llama/llama-3.3-70b-instruct",
        name: "meta-llama/llama-3.3-70b-instruct",
        label: "Llama 3.3 70B (via OpenRouter)",
        provider: "openrouter",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Meta's latest 70B instruct model.",
        arabicDescription: "أحدث نموذج 70B من Meta.",
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    arabicName: "Groq",
    description: "Ultra-fast inference for Llama, Mixtral, and more.",
    arabicDescription: "استدعاء فائق السرعة لنماذج Llama و Mixtral.",
    protocol: "openai-chat",
    baseUrl: "https://api.groq.com/openai/v1",
    docsUrl: "https://console.groq.com/docs",
    apiKeyUrl: "https://console.groq.com/keys",
    serverEnvKey: "GROQ_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#F55036",
    popularModels: [
      {
        id: "llama-3.3-70b-versatile",
        name: "llama-3.3-70b-versatile",
        label: "Llama 3.3 70B",
        provider: "groq",
        contextWindow: 128000,
        maxOutput: 32768,
        pricing: "freemium",
        description: "Llama 3.3 70B running on Groq's LPU.",
        arabicDescription: "Llama 3.3 70B على معالجات Groq LPU.",
      },
      {
        id: "llama-3.1-8b-instant",
        name: "llama-3.1-8b-instant",
        label: "Llama 3.1 8B Instant",
        provider: "groq",
        contextWindow: 128000,
        maxOutput: 8192,
        pricing: "free",
        description: "Sub-second latency 8B model.",
        arabicDescription: "زمن استجابة أقل من ثانية.",
      },
      {
        id: "deepseek-r1-distill-llama-70b",
        name: "deepseek-r1-distill-llama-70b",
        label: "DeepSeek R1 Distill 70B",
        provider: "groq",
        contextWindow: 128000,
        maxOutput: 32768,
        pricing: "freemium",
        description: "Reasoning model distilled to Llama 70B.",
        arabicDescription: "نموذج استدلالي مُقطّر على Llama 70B.",
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    arabicName: "DeepSeek",
    description: "DeepSeek V3 and R1 reasoning models.",
    arabicDescription: "نماذج DeepSeek V3 و R1 الاستدلالية.",
    protocol: "openai-chat",
    baseUrl: "https://api.deepseek.com/v1",
    docsUrl: "https://api-docs.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    serverEnvKey: "DEEPSEEK_API_KEY",
    supportsStreaming: true,
    supportsVision: false,
    accent: "#4D6BFE",
    popularModels: [
      {
        id: "deepseek-chat",
        name: "deepseek-chat",
        label: "DeepSeek V3",
        provider: "deepseek",
        contextWindow: 64000,
        maxOutput: 8192,
        pricing: "paid",
        description: "DeepSeek V3 general-purpose chat model.",
        arabicDescription: "نموذج DeepSeek V3 العام.",
      },
      {
        id: "deepseek-reasoner",
        name: "deepseek-reasoner",
        label: "DeepSeek R1",
        provider: "deepseek",
        contextWindow: 64000,
        maxOutput: 8192,
        pricing: "paid",
        description: "Reasoning model with chain-of-thought.",
        arabicDescription: "نموذج استدلالي بسلسلة تفكير.",
      },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    arabicName: "Together AI",
    description: "Hosted open-source models with OpenAI-compatible API.",
    arabicDescription: "نماذج مفتوحة المصدر مستضافة بواجهة OpenAI.",
    protocol: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    docsUrl: "https://docs.together.ai",
    apiKeyUrl: "https://api.together.ai/settings/api-keys",
    serverEnvKey: "TOGETHER_API_KEY",
    supportsStreaming: true,
    supportsVision: false,
    accent: "#0F6FFF",
    popularModels: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        label: "Llama 3.3 70B Turbo",
        provider: "together",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Llama 3.3 70B optimized for Together.",
        arabicDescription: "Llama 3.3 70B محسّن لـ Together.",
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        name: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        label: "Qwen 2.5 72B Turbo",
        provider: "together",
        contextWindow: 32768,
        pricing: "freemium",
        description: "Strong multilingual model from Alibaba.",
        arabicDescription: "نموذج متعدد اللغات قوي من Alibaba.",
      },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    arabicName: "Fireworks AI",
    description: "Fast inference for open-source LLMs and vision models.",
    arabicDescription: "استدعاء سريع للنماذج مفتوحة المصدر.",
    protocol: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    docsUrl: "https://docs.fireworks.ai",
    apiKeyUrl: "https://fireworks.ai/account/api-keys",
    serverEnvKey: "FIREWORKS_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#E25A1C",
    popularModels: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        name: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        label: "Llama 3.3 70B (Fireworks)",
        provider: "fireworks",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Llama 3.3 70B on Fireworks.",
        arabicDescription: "Llama 3.3 70B على Fireworks.",
      },
      {
        id: "accounts/fireworks/models/qwen2p5-72b-instruct",
        name: "accounts/fireworks/models/qwen2p5-72b-instruct",
        label: "Qwen 2.5 72B (Fireworks)",
        provider: "fireworks",
        contextWindow: 32768,
        pricing: "freemium",
        description: "Qwen 2.5 72B on Fireworks.",
        arabicDescription: "Qwen 2.5 72B على Fireworks.",
      },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    arabicName: "NVIDIA NIM",
    description: "NVIDIA's hosted inference microservices for leading models.",
    arabicDescription: "خدمات NVIDIA NIM للاستدعاء المستضاف.",
    protocol: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    docsUrl: "https://docs.api.nvidia.com/nim/reference",
    apiKeyUrl: "https://build.nvidia.com/",
    serverEnvKey: "NVIDIA_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#76B900",
    popularModels: [
      {
        id: "meta/llama-3.3-70b-instruct",
        name: "meta/llama-3.3-70b-instruct",
        label: "Llama 3.3 70B (NIM)",
        provider: "nvidia",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Llama 3.3 70B on NVIDIA NIM.",
        arabicDescription: "Llama 3.3 70B على NVIDIA NIM.",
      },
      {
        id: "deepseek-ai/deepseek-r1",
        name: "deepseek-ai/deepseek-r1",
        label: "DeepSeek R1 (NIM)",
        provider: "nvidia",
        contextWindow: 128000,
        pricing: "freemium",
        description: "DeepSeek R1 on NVIDIA NIM.",
        arabicDescription: "DeepSeek R1 على NVIDIA NIM.",
      },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    arabicName: "Hugging Face",
    description: "Serverless inference for 200,000+ models.",
    arabicDescription: "استدعاء بدون خادم لأكثر من 200,000 نموذج.",
    protocol: "openai-chat",
    baseUrl: "https://api-inference.huggingface.co/v1",
    docsUrl: "https://huggingface.co/docs/api-inference",
    apiKeyUrl: "https://huggingface.co/settings/tokens",
    serverEnvKey: "HUGGINGFACE_API_KEY",
    supportsStreaming: true,
    supportsVision: false,
    accent: "#FFD21E",
    popularModels: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "meta-llama/Llama-3.3-70B-Instruct",
        label: "Llama 3.3 70B (HF)",
        provider: "huggingface",
        contextWindow: 128000,
        pricing: "freemium",
        description: "Llama 3.3 70B on Hugging Face Inference.",
        arabicDescription: "Llama 3.3 70B على Hugging Face.",
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen/Qwen2.5-72B-Instruct",
        label: "Qwen 2.5 72B (HF)",
        provider: "huggingface",
        contextWindow: 32768,
        pricing: "freemium",
        description: "Qwen 2.5 72B on Hugging Face.",
        arabicDescription: "Qwen 2.5 72B على Hugging Face.",
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    arabicName: "Mistral",
    description: "Mistral Large, Medium, and Codestral from Europe.",
    arabicDescription: "Mistral Large و Medium و Codestral من أوروبا.",
    protocol: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    docsUrl: "https://docs.mistral.ai",
    apiKeyUrl: "https://console.mistral.ai/api-keys",
    serverEnvKey: "MISTRAL_API_KEY",
    supportsStreaming: true,
    supportsVision: true,
    accent: "#FF7000",
    popularModels: [
      {
        id: "mistral-large-latest",
        name: "mistral-large-latest",
        label: "Mistral Large",
        provider: "mistral",
        contextWindow: 128000,
        maxOutput: 8192,
        pricing: "paid",
        description: "Top-tier Mistral model for complex tasks.",
        arabicDescription: "أقوى نموذج Mistral للمهام المعقدة.",
      },
      {
        id: "mistral-medium-latest",
        name: "mistral-medium-latest",
        label: "Mistral Medium",
        provider: "mistral",
        contextWindow: 32000,
        pricing: "paid",
        description: "Balanced model for general use.",
        arabicDescription: "نموذج متوازن للاستخدام العام.",
      },
      {
        id: "codestral-latest",
        name: "codestral-latest",
        label: "Codestral",
        provider: "mistral",
        contextWindow: 32000,
        pricing: "paid",
        description: "Specialized for code generation.",
        arabicDescription: "متخصص في توليد الأكواد.",
      },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    arabicName: "Cohere",
    description: "Command R+ and Command R for enterprise use cases.",
    arabicDescription: "Command R+ و Command R للاستخدام المؤسسي.",
    protocol: "cohere",
    baseUrl: "https://api.cohere.com/v2",
    docsUrl: "https://docs.cohere.com",
    apiKeyUrl: "https://dashboard.cohere.com/api-keys",
    serverEnvKey: "COHERE_API_KEY",
    supportsStreaming: true,
    supportsVision: false,
    accent: "#39594D",
    popularModels: [
      {
        id: "command-r-plus-08-2024",
        name: "command-r-plus-08-2024",
        label: "Command R+",
        provider: "cohere",
        contextWindow: 128000,
        maxOutput: 4000,
        pricing: "paid",
        description: "Cohere's flagship retrieval-augmented model.",
        arabicDescription: "نموذج Cohere الرئيسي للاسترجاع المعزز.",
      },
      {
        id: "command-r-08-2024",
        name: "command-r-08-2024",
        label: "Command R",
        provider: "cohere",
        contextWindow: 128000,
        maxOutput: 4000,
        pricing: "paid",
        description: "Scalable model for business workloads.",
        arabicDescription: "نموذج قابل للتوسع لأحمال العمل المؤسسية.",
      },
    ],
  },
  {
    id: "openai-compatible",
    name: "OpenAI Compatible",
    arabicName: "متوافق مع OpenAI",
    description: "Bring your own OpenAI-compatible endpoint (LM Studio, vLLM, Ollama, etc.).",
    arabicDescription: "أدخل نقطة نهاية متوافقة مع OpenAI (LM Studio, vLLM, Ollama، إلخ).",
    protocol: "openai-chat",
    baseUrl: "http://localhost:1234/v1",
    docsUrl: "https://platform.openai.com/docs/api-reference",
    apiKeyUrl: "",
    supportsStreaming: true,
    supportsVision: false,
    accent: "#64748B",
    popularModels: [
      {
        id: "local-model",
        name: "local-model",
        label: "Local Model",
        provider: "openai-compatible",
        contextWindow: 8192,
        pricing: "free",
        description: "Default placeholder for any OpenAI-compatible endpoint.",
        arabicDescription: "عنصر نائب افتراضي لأي نقطة نهاية متوافقة مع OpenAI.",
      },
    ],
  },
];

export const PROVIDER_MAP: Record<ProviderId, ProviderDefinition> =
  PROVIDER_CATALOG.reduce(
    (acc, p) => {
      acc[p.id] = p;
      return acc;
    },
    {} as Record<ProviderId, ProviderDefinition>,
  );

export function getProvider(id: ProviderId): ProviderDefinition {
  return PROVIDER_MAP[id];
}

/** Type-guard: is this string a known ProviderId? Shared by every API route that validates one. */
export function isValidProviderId(id: string): id is ProviderId {
  return Object.prototype.hasOwnProperty.call(PROVIDER_MAP, id);
}

export function getAllModels(): import("./types").ModelDefinition[] {
  return PROVIDER_CATALOG.flatMap((p) => p.popularModels);
}
